apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-rabbitmq-0
  labels:
    app: rabbitmq
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data-rabbitmq-0
