apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-data-kafka-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  hostPath:
    path: /mnt/data/kafka-data-kafka-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zookeeper-data-zookeeper-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  hostPath:
    path: /mnt/data/zookeeper-data-zookeeper-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zookeeper-log-zookeeper-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  hostPath:
    path: /mnt/data/zookeeper-log-zookeeper-0
